# Generated by Django 3.0.8 on 2020-12-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Excercise',
            new_name='Exercise',
        ),
    ]
