version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    working_dir: /app
    tty: true
    expose:
      - "5000"
    ports:
      - 0.0.0.0:5000:5000
    volumes:
      - .:/app
